# Generated by Django 4.0 on 2021-12-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customers_orders_orderitem_donations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donations',
            name='price',
        ),
    ]
