# Generated by Django 4.0 on 2021-12-29 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_donations_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='dateDonation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
