# Generated by Django 4.0 on 2022-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_donations_datedonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('short_description', models.TextField(blank=True, default='', null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='images/solutions')),
                ('type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('benefit_1', models.TextField(blank=True, default='', null=True)),
                ('benefit_2', models.TextField(blank=True, default='', null=True)),
                ('benefit_3', models.TextField(blank=True, default='', null=True)),
                ('data_1', models.TextField(blank=True, default='', null=True)),
                ('data_2', models.TextField(blank=True, default='', null=True)),
                ('data_3', models.TextField(blank=True, default='', null=True)),
                ('data_4', models.TextField(blank=True, default='', null=True)),
                ('phrase', models.TextField(blank=True, default='', null=True)),
                ('phrase_author', models.TextField(blank=True, default='', null=True)),
                ('icon', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
