# Generated by Django 4.0 on 2022-01-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_solutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='image',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
