# Generated by Django 4.0 on 2022-01-12 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_solutions_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='dateRegister',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orders',
            name='datePurchase',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
