# Generated by Django 4.0 on 2022-02-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_reports_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customers',
            name='gender',
            field=models.CharField(blank=True, default='Not specified', max_length=100, null=True),
        ),
    ]
