# Generated by Django 4.0 on 2022-02-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_customers_age_customers_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='wantsToReceiveEmails',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
